In [2]:
import torch
import torch.nn as nn

/home/zhangjx/anaconda3/envs/deeplearning/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [7]:
w = torch.empty(3, 5)
nn.init.kaiming_normal_(w, mode='fan_out', nonlinearity='relu')


tensor([[ 0.0602,  0.2154, -0.4319,  1.8092, -0.1422],
        [ 1.0375, -0.5171,  0.6319, -0.6884,  0.1758],
        [-0.5527, -0.4267, -1.2458,  0.1051,  0.5504]])

In [13]:
# a=0, b=1 之间的均匀分布
w = torch.empty(3, 5)
nn.init.uniform_(w)

tensor([[0.7804, 0.6556, 0.6133, 0.7155, 0.3909],
        [0.7227, 0.7625, 0.4693, 0.9875, 0.4691],
        [0.8771, 0.7359, 0.9151, 0.8631, 0.9846]])

In [ ]:
# mean=0, std=1 的高斯分布
w = torch.empty(3, 5)
nn.init.normal_(w)

In [15]:
# 常值分布, 所有元素为一给定值
w = torch.empty(3, 5)
nn.init.constant_(w,0.3)

tensor([[0.3000, 0.3000, 0.3000, 0.3000, 0.3000],
        [0.3000, 0.3000, 0.3000, 0.3000, 0.3000],
        [0.3000, 0.3000, 0.3000, 0.3000, 0.3000]])

In [16]:
# 仅作用于二维张量, 主对角分布
w = torch.empty(3, 5)
nn.init.eye_(w)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])

In [ ]:
# 仅作用于三、四、五维张量, 狄拉克函数
w = torch.empty(3, 16, 5, 5)
nn.init.dirac_(w)
nn.init.dirac_(w, 3)